// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Buy struct {
	Promo    *string `json:"promo"`
	Nickname string  `json:"nickname"`
	Pay      int     `json:"pay"`
	Cart     []*Cart `json:"Cart"`
}

type BuyInput struct {
	Promo    string       `json:"promo"`
	Nickname string       `json:"nickname"`
	Pay      int          `json:"pay"`
	Cart     []*CartInput `json:"Cart"`
}

type Cart struct {
	ID    string  `json:"id"`
	Items []*Item `json:"items"`
	Count int     `json:"count"`
}

type CartInput struct {
	ID    string       `json:"id"`
	Item  []*ItemInput `json:"item"`
	Count int          `json:"count"`
}

type ItemInput struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Price     int    `json:"price"`
	Desc      string `json:"desc"`
	Discprice int    `json:"discprice"`
}

type Minecraft struct {
	OnlinePlayers int `json:"onlinePlayers"`
}
